export const availableCategories = [
  "#1", 
  "Work", 
  "Fitness", 
  "Habit", 
  "Journal", 
  "Complete", 
  "Uncategorized",
  "Urgent",
  "Flomigo",
  "Project Ideas",
  "App Ideas",
  "Ideas",
  "Family",
  "Personal",
  "Discuss",
  "Delegate",
  "Work Day",
  "Follow-Up",
  "Meetings"
];