export const styleOptions = [
  { id: 'abstract', label: 'Abstract Art' },
  { id: 'ad', label: 'Advertisement' },
  { id: 'website', label: 'Website Photos' },
  { id: 'background', label: 'Background Images' },
  { id: 'warm', label: 'Warm Tones' },
  { id: 'cold', label: 'Cold Tones' },
  { id: 'bw', label: 'Black and White' },
  { id: 'minimalist', label: 'Minimalist' },
  { id: 'vintage', label: 'Vintage' },
  { id: 'futuristic', label: 'Futuristic' },
  { id: 'nature', label: 'Nature-inspired' },
  { id: 'geometric', label: 'Geometric' },
  { id: 'photorealistic', label: 'Photorealistic' },
  { id: 'cinematic', label: 'Cinematic' },
  { id: 'anime', label: 'Anime Style' },
  { id: '3d', label: '3D Rendered' },
  { id: 'watercolor', label: 'Watercolor' },
  { id: 'oil-painting', label: 'Oil Painting' },
  { id: 'pencil-sketch', label: 'Pencil Sketch' },
  { id: 'digital-art', label: 'Digital Art' },
  { id: 'studio-photo', label: 'Studio Photography' },
  { id: 'isometric', label: 'Isometric' },
  { id: 'low-poly', label: 'Low Poly' },
  { id: 'pixel-art', label: 'Pixel Art' }
];